### List all messages
GET http://localhost:3000/messages


### Get a particular message
GET http://localhost:3000/messages/101


### Create a new message 
POST http://localhost:3000/messages
content-type: application/json

{
  "message": "New message"
}